[workspace]
members = ["step07"]
resolver = "2"

[workspace.dependencies]
burn = { version = "0.17", features = ["ndarray", "train", "std"] }
burn-ndarray = "0.17"
burn-autodiff = "0.17"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"