[package]
name = "step07"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { workspace = true }
burn-ndarray = { workspace = true }
burn-autodiff = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }